configured_endpoints: 59
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/dinari--inc-dash%2Fdinari-801a7c69b83ef0f52a623d63eddb0fd36ccbdee1ac4b3f9568a66828bbdc7f76.yml
openapi_spec_hash: 7bb025731f8baf9eab094b0bf88ac5e3
config_hash: c0cf73d660e24bc7c861ee47fceb4693
