configured_endpoints: 55
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/dinari--inc-dash%2Fdinari-e99ec49210c48a4a70d637a7dec9aa48d96c4baffa9ed98c24d72a85b95a5c92.yml
openapi_spec_hash: 7cf9b803fdccc473bcdd84996d32b4ec
config_hash: a34fcee2d6dea5d681cf7406b0b4d48e
